name: oaf
channels:
  - conda-forge
dependencies:
  - networkx
  - numpy
  - seaborn
  - pip
  - pip:
      # Install SPA library from GitHub using SSH
      - "git+https://git@github.com/filipmazurek/spa-library@v0.0.1"
      # Local installation
      - -e ./
